language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: hhvm
      dist: trusty

sudo: false

before_install: phpenv config-rm xdebug.ini || true
  
install: composer dump-autoload

script: phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
